disabled = false
languageCode = "de"
languageName = "Deutsch"
weight = 1
title = "Kristina & Hannes Hochzeitsparty"

[params]
displayName = "DE"
isoCode = "de"
rtl = false
dateFormat = "2 January 2006"
