disabled = false
languageCode = "de"
languageName = "Deutsch"
weight = 1
title = "K&H Party"

[params]
displayName = "DE"
isoCode = "de"
rtl = false
dateFormat = "2 January 2006"
logo = "img/krishahochzeit_logo.png"
